import './displayStats.test';
import './personalRecords.test';
import './monthlyStats.test';
import './activityAggregationPolicy.test';
import './presence.test';
import './processContributions.test';
import './routeSplits.test';
import './gpsQuality.test';
import './gpsProcessing.test';
import './battleCredit.test';
import './invite.test';
import './reviewFixes.test';
import './moderation.test';
import './battleSelection.test';
import './runShare.test';
import './battleParticipation.test';
import './battleTerms.test';
import './declarations.test';
import './avatarEmojis.test';
import './designTokens.test';
import './providerButtons.test';
import './localizationMarket.test';
import './releaseHardening.test';
import './rankNotificationTiming.test';
import './stepCounter.test';

console.log('all unit tests passed');
